name: gudangku
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  image_picker: ^1.0.0
  provider: 5.0.0
  cupertino_icons: ^1.0.8
  intl: ^0.18.1
  pdf: ^3.10.4
  printing: ^5.11.0
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/images/a.jpg
    - lib/images/ab.jpeg
    - lib/images/ab-removebg-preview.png
    
